"""model v2

Revision ID: 051ce3f3636a
Revises: fd883b1c1426
Create Date: 2025-09-23 12:11:59.254506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051ce3f3636a'
down_revision = 'fd883b1c1426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Ingredient',
    sa.Column('ingredient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vegetarian', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('pizza_ingredient',
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['Ingredient.ingredient_id'], ),
    sa.ForeignKeyConstraint(['pizza_id'], ['Pizza.pizza_id'], ),
    sa.PrimaryKeyConstraint('pizza_id', 'ingredient_id')
    )
    op.drop_table('discount_list')
    op.drop_table('pizza_ingredients')
    op.drop_table('Ingredients')
    op.drop_table('deliveryperson_order')
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('DiscountCode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'DiscountType', ['discount_type_id'], ['discount_type_id'])

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('discount_code_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.alter_column('discount_code_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('time_stamp')

    with op.batch_alter_table('DiscountCode', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('discount_type_id')

    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')

    op.create_table('deliveryperson_order',
    sa.Column('delivery_person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['delivery_person_id'], ['DeliveryPerson.delivery_person_id'], name=op.f('deliveryperson_order_delivery_person_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['Order.order_id'], name=op.f('deliveryperson_order_order_id_fkey')),
    sa.PrimaryKeyConstraint('delivery_person_id', 'order_id', name=op.f('deliveryperson_order_pkey'))
    )
    op.create_table('pizza_ingredients',
    sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['Ingredients.ingredient_id'], name=op.f('pizza_ingredients_ingredient_id_fkey')),
    sa.ForeignKeyConstraint(['pizza_id'], ['Pizza.pizza_id'], name=op.f('pizza_ingredients_pizza_id_fkey')),
    sa.PrimaryKeyConstraint('pizza_id', 'ingredient_id', name=op.f('pizza_ingredients_pkey'))
    )
    op.create_table('Ingredients',
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('vegetarian', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id', name=op.f('Ingredients_pkey'))
    )
    op.create_table('discount_list',
    sa.Column('discount_code_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discount_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['discount_code_id'], ['DiscountCode.discount_code_id'], name=op.f('discount_list_discount_code_id_fkey')),
    sa.ForeignKeyConstraint(['discount_type_id'], ['DiscountType.discount_type_id'], name=op.f('discount_list_discount_type_id_fkey')),
    sa.PrimaryKeyConstraint('discount_code_id', 'discount_type_id', name=op.f('discount_list_pkey'))
    )
    op.drop_table('pizza_ingredient')
    op.drop_table('Ingredient')
    op.drop_table('Admin')
    # ### end Alembic commands ###
