"""models v3 with seeded data

Revision ID: 0daf1082b116
Revises: 051ce3f3636a
Create Date: 2025-09-30 14:10:22.692854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0daf1082b116'
down_revision = '051ce3f3636a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pizza', schema=None) as batch_op:
        batch_op.drop_column('ingredients_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pizza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients_text', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
