"""Addede live order tracking

Revision ID: 847890d26b72
Revises: c29600af9ca3
Create Date: 2025-10-20 18:32:50.696293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847890d26b72'
down_revision = 'c29600af9ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
