"""Initial migration from existing schema

Revision ID: 892553e6bd44
Revises: 
Create Date: 2025-10-20 17:51:34.687689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892553e6bd44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DeliveryPerson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_assigned_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('Pizza', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pizza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))

    with op.batch_alter_table('DeliveryPerson', schema=None) as batch_op:
        batch_op.drop_column('last_assigned_at')

    # ### end Alembic commands ###
