"""newe schema

Revision ID: 9c621d1e0752
Revises: 847890d26b72
Create Date: 2025-10-21 19:08:21.710870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c621d1e0752'
down_revision = '847890d26b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.SMALLINT(),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
        batch_op.alter_column('loyalty_pizza_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::bigint"))

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.alter_column('delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.alter_column('delivered_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.alter_column('loyalty_pizza_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))

    # ### end Alembic commands ###
