"""Add gender column with default

Revision ID: a9009c23ba2d
Revises: 0daf1082b116
Create Date: 2025-10-20 17:27:13.474621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9009c23ba2d'
down_revision = '0daf1082b116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.SmallInteger(), 
                                      server_default='0', nullable=False))
        batch_op.alter_column('postal_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_customer_postal_code'))

    with op.batch_alter_table('DeliveryPerson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.String(length=10), nullable=True))

    with op.batch_alter_table('delivery_person_postal_range', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_dppr_bounds'))
        batch_op.drop_constraint(batch_op.f('delivery_person_postal_range_delivery_person_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'DeliveryPerson', ['delivery_person_id'], ['delivery_person_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_person_postal_range', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('delivery_person_postal_range_delivery_person_id_fkey'), 'DeliveryPerson', ['delivery_person_id'], ['delivery_person_id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_dppr_bounds'), ['start_zip', 'end_zip'], unique=False)

    with op.batch_alter_table('DeliveryPerson', schema=None) as batch_op:
        batch_op.drop_column('postal_code')

    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_customer_postal_code'), ['postal_code'], unique=False)
        batch_op.alter_column('postal_code',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
