"""initial migration

Revision ID: fd883b1c1426
Revises: 
Create Date: 2025-09-19 16:51:03.649779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd883b1c1426'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customer',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('DeliveryPerson',
    sa.Column('delivery_person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('delivery_person_id')
    )
    op.create_table('Order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discount_code_id', sa.Integer(), nullable=False),
    sa.Column('delivery_person_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['Customer.customer_id'], ),
    sa.ForeignKeyConstraint(['delivery_person_id'], ['DeliveryPerson.delivery_person_id'], ),
    sa.ForeignKeyConstraint(['discount_code_id'], ['DiscountCode.discount_code_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('discount_list',
    sa.Column('discount_code_id', sa.Integer(), nullable=False),
    sa.Column('discount_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discount_code_id'], ['DiscountCode.discount_code_id'], ),
    sa.ForeignKeyConstraint(['discount_type_id'], ['DiscountType.discount_type_id'], ),
    sa.PrimaryKeyConstraint('discount_code_id', 'discount_type_id')
    )
    op.create_table('OrderItem',
    sa.Column('order_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['Order.order_id'], ),
    sa.ForeignKeyConstraint(['pizza_id'], ['Pizza.pizza_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_table('deliveryperson_order',
    sa.Column('delivery_person_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_person_id'], ['DeliveryPerson.delivery_person_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['Order.order_id'], ),
    sa.PrimaryKeyConstraint('delivery_person_id', 'order_id')
    )
    op.drop_table('Customers')
    with op.batch_alter_table('Pizza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pizza', schema=None) as batch_op:
        batch_op.drop_column('price')

    op.create_table('Customers',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('telephone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('Customers_pkey'))
    )
    op.drop_table('deliveryperson_order')
    op.drop_table('OrderItem')
    op.drop_table('discount_list')
    op.drop_table('Order')
    op.drop_table('DeliveryPerson')
    op.drop_table('Customer')
    # ### end Alembic commands ###
